-- Northwind Trading Co. - sample database for the Claude Labs Data Track
-- Fictional data. Generated by build_data.py - do not edit by hand.
-- Tested against MySQL 8.x. Run with:  SOURCE northwind-setup.sql

DROP DATABASE IF EXISTS northwind;
CREATE DATABASE northwind;
USE northwind;

-- ---------------------------------------------------------------
-- Customer master. One row per customer - the whole point of a
-- relational database is that this name is stored exactly once.
-- ---------------------------------------------------------------
CREATE TABLE customers (
  customer_id        CHAR(4)       NOT NULL,
  customer_name      VARCHAR(80)   NOT NULL,
  region             VARCHAR(20)       NULL,
  payment_terms_days INT           NOT NULL DEFAULT 30,
  credit_limit       DECIMAL(12,2) NOT NULL,
  account_manager    VARCHAR(40)       NULL,
  PRIMARY KEY (customer_id)
) ENGINE=InnoDB;

INSERT INTO customers
  (customer_id, customer_name, region, payment_terms_days, credit_limit, account_manager)
VALUES
  ('C001', 'Argent Retail Group', 'North', 30, 100000.00, 'R. Aldridge'),
  ('C002', 'Brightwater Industries', 'South', 30, 150000.00, 'R. Aldridge'),
  ('C003', 'Copperfield & Sons', NULL, 30, 100000.00, 'M. Okafor'),
  ('C004', 'Dunmore Wholesale', 'East', 30, 150000.00, 'M. Okafor'),
  ('C005', 'Eastvale Distribution', 'East', 30, 150000.00, 'M. Okafor'),
  ('C006', 'Fairlight Mercantile', 'West', 30, 125000.00, 'S. K. Rao'),
  ('C007', 'Granite Bay Outfitters', '', 30, 100000.00, 'S. K. Rao'),
  ('C008', 'Holloway Supply Co', 'North', 30, 125000.00, 'R. Aldridge'),
  ('C009', 'Ironwood Partners', NULL, 30, 100000.00, 'S. K. Rao'),
  ('C010', 'Juniper Mercantile', 'South', 30, 125000.00, 'M. Okafor');

-- ---------------------------------------------------------------
-- Open sales invoices at 30 June 2026. customer_id is a foreign key
-- back to customers - and it is NULL on one row, which is on purpose.
-- ---------------------------------------------------------------
CREATE TABLE invoices (
  invoice_no     VARCHAR(12)   NOT NULL,
  customer_id    CHAR(4)           NULL,
  invoice_date   DATE          NOT NULL,
  due_date       DATE          NOT NULL,
  amount         DECIMAL(12,2) NOT NULL,
  days_past_due  INT           NOT NULL,
  aging_bucket   VARCHAR(10)   NOT NULL,
  PRIMARY KEY (invoice_no),
  CONSTRAINT fk_invoices_customer
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
) ENGINE=InnoDB;

INSERT INTO invoices
  (invoice_no, customer_id, invoice_date, due_date, amount, days_past_due, aging_bucket)
VALUES
  ('INV-4382', 'C001', '2026-05-21', '2026-06-20', 37303.23, 10, '31-60'),
  ('INV-4383', 'C001', '2026-05-21', '2026-06-20', 26523.83, 10, '31-60'),
  ('INV-4391', NULL, '2026-02-10', '2026-03-12', 22010.93, 110, '90+'),
  ('INV-4387', 'C002', '2026-06-18', '2026-07-18', 58785.79, 0, 'Current'),
  ('INV-4393', 'C002', '2026-06-18', '2026-07-18', 16356.36, 0, 'Current'),
  ('INV-4403', 'C003', '2026-03-22', '2026-04-21', 27749.80, 70, '90+'),
  ('INV-4399', 'C003', '2026-05-06', '2026-06-05', 29211.81, 25, '31-60'),
  ('INV-4397', 'C003', '2026-05-21', '2026-06-20', 58179.54, 10, '31-60'),
  ('INV-4410', 'C004', '2026-03-22', '2026-04-21', 11369.08, 70, '90+'),
  ('INV-4406', 'C004', '2026-06-05', '2026-07-05', 57507.26, 0, 'Current'),
  ('INV-4415', 'C004', '2026-06-05', '2026-07-05', 53241.93, 0, 'Current'),
  ('INV-4411', 'C004', '2026-06-18', '2026-07-18', 45170.64, 0, 'Current'),
  ('INV-4417', 'C004', '2026-06-18', '2026-07-18', 53941.27, 0, 'Current'),
  ('INV-4427', 'C005', '2026-05-06', '2026-06-05', 50482.77, 25, '31-60'),
  ('INV-4431', 'C005', '2026-05-21', '2026-06-20', 14930.84, 10, '31-60'),
  ('INV-4423', 'C005', '2026-06-05', '2026-07-05', 17356.89, 0, 'Current'),
  ('INV-4421', 'C005', '2026-06-18', '2026-07-18', 25898.06, 0, 'Current'),
  ('INV-4439', 'C006', '2026-06-05', '2026-07-05', 38645.42, 0, 'Current'),
  ('INV-4435', 'C006', '2026-06-18', '2026-07-18', 55638.15, 0, 'Current'),
  ('INV-4442', 'C007', '2026-05-21', '2026-06-20', 11822.00, 10, '31-60'),
  ('INV-4447', 'C007', '2026-05-21', '2026-06-20', 12050.79, 10, '31-60'),
  ('INV-4446', 'C007', '2026-06-18', '2026-07-18', 53265.30, 0, 'Current'),
  ('INV-4452', 'C008', '2026-04-16', '2026-05-16', 51492.30, 45, '61-90'),
  ('INV-4450', 'C008', '2026-06-05', '2026-07-05', 53177.09, 0, 'Current'),
  ('INV-4462', 'C009', '2026-02-10', '2026-03-12', 55699.51, 110, '90+'),
  ('INV-4458', 'C009', '2026-04-16', '2026-05-16', 6951.61, 45, '61-90'),
  ('INV-4455', 'C009', '2026-06-05', '2026-07-05', 22607.88, 0, 'Current'),
  ('INV-4457', 'C009', '2026-06-05', '2026-07-05', 20028.77, 0, 'Current'),
  ('INV-4460', 'C009', '2026-06-05', '2026-07-05', 8275.39, 0, 'Current'),
  ('INV-4466', 'C009', '2026-06-18', '2026-07-18', 8835.27, 0, 'Current'),
  ('INV-4472', 'C010', '2026-05-06', '2026-06-05', 15465.17, 25, '31-60'),
  ('INV-4469', 'C010', '2026-06-05', '2026-07-05', 26369.53, 0, 'Current'),
  ('INV-4470', 'C010', '2026-06-05', '2026-07-05', 6999.37, 0, 'Current'),
  ('INV-4473', 'C010', '2026-06-18', '2026-07-18', 43008.71, 0, 'Current');

-- ---------------------------------------------------------------
-- June cash ledger. Note account_name is repeated on every single
-- row - that is what a denormalised table looks like.
-- ---------------------------------------------------------------
CREATE TABLE gl_entries (
  entry_no     VARCHAR(10)   NOT NULL,
  entry_date   DATE          NOT NULL,
  account_code VARCHAR(10)   NOT NULL,
  account_name VARCHAR(60)   NOT NULL,
  description  VARCHAR(120)  NOT NULL,
  reference    VARCHAR(20)       NULL,
  debit        DECIMAL(12,2)     NULL,
  credit       DECIMAL(12,2)     NULL,
  memo         VARCHAR(120)      NULL,
  PRIMARY KEY (entry_no)
) ENGINE=InnoDB;

INSERT INTO gl_entries
  (entry_no, entry_date, account_code, account_name, description, reference, debit, credit, memo)
VALUES
  ('JE-2601', '2026-06-02', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - ARGENT RETAIL GROUP', 'INV-4471', 48200.00, NULL, NULL),
  ('JE-2602', '2026-06-03', '1010', 'Cash - Operating', 'CHECK #10471 - NORTHGATE PROPERTY MGMT', 'CHK10471', NULL, 26000.00, 'June rent'),
  ('JE-2603', '2026-06-04', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - DUNMORE WHOLESALE', 'INV-4468', 22450.00, NULL, NULL),
  ('JE-2604', '2026-06-05', '1010', 'Cash - Operating', 'CHECK #10472 - PACIFIC MATERIALS SUPPLY', 'CHK10472', NULL, 84200.00, 'PO-8821'),
  ('JE-2605', '2026-06-05', '1010', 'Cash - Operating', 'CHECK #10473 - SUMMIT OFFICE SUPPLY', 'CHK10473', NULL, 3480.00, 'PO-8834'),
  ('JE-2606', '2026-06-08', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - BRIGHTWATER INDUSTRIES', 'INV-4475', 61800.00, NULL, NULL),
  ('JE-2607', '2026-06-09', '1010', 'Cash - Operating', 'CHECK #10474 - MERIDIAN STAFFING', 'CHK10474', NULL, 41900.00, 'Week 22 contract labor'),
  ('JE-2608', '2026-06-10', '1010', 'Cash - Operating', 'CHECK #10475 - CASCADE LOGISTICS', 'CHK10475', NULL, 18740.00, 'Freight - May'),
  ('JE-2609', '2026-06-11', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - EASTVALE DISTRIBUTION', 'INV-4479', 15900.00, NULL, NULL),
  ('JE-2610', '2026-06-12', '1010', 'Cash - Operating', 'CHECK #10476 - ORION SOFTWARE LTD', 'CHK10476', NULL, 14200.00, 'Annual license'),
  ('JE-2611', '2026-06-12', '1010', 'Cash - Operating', 'CHECK #10476 - ORION SOFTWARE LTD', 'CHK10476', NULL, 14200.00, 'Annual license (re-posted)'),
  ('JE-2612', '2026-06-12', '1010', 'Cash - Operating', 'CHECK #10477 - BLUE RIDGE UTILITIES', 'CHK10477', NULL, 6820.00, 'Utilities - May'),
  ('JE-2613', '2026-06-13', '1010', 'Cash - Operating', 'CHECK #10478 - SUMMIT OFFICE SUPPLY', 'CHK10478', NULL, 1452.00, 'PO-8858'),
  ('JE-2614', '2026-06-15', '1010', 'Cash - Operating', 'PAYROLL ACH - PERIOD ENDING 06/13', 'ACH', NULL, 128400.00, NULL),
  ('JE-2615', '2026-06-15', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - COPPERFIELD & SONS', 'INV-4482', 38400.00, NULL, NULL),
  ('JE-2616', '2026-06-16', '1010', 'Cash - Operating', 'CHECK #10479 - PACIFIC MATERIALS SUPPLY', 'CHK10479', NULL, 67300.00, 'PO-8849'),
  ('JE-2617', '2026-06-17', '1010', 'Cash - Operating', 'CHECK #10480 - HARBOR POINT INSURANCE', 'CHK10480', NULL, 18600.00, 'Q2 premium'),
  ('JE-2618', '2026-06-18', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - ARGENT RETAIL GROUP', 'INV-4488', 27650.00, NULL, NULL),
  ('JE-2619', '2026-06-19', '1010', 'Cash - Operating', 'CHECK #10481 - DELTA FREIGHT SERVICES', 'CHK10481', NULL, 12480.00, 'Freight - Jun wk1-2'),
  ('JE-2620', '2026-06-20', '1010', 'Cash - Operating', 'CORPORATE CARD SETTLEMENT', 'ACH', NULL, 24380.00, NULL),
  ('JE-2621', '2026-06-22', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - FAIRLIGHT MERCANTILE', 'INV-4491', 44100.00, NULL, NULL),
  ('JE-2622', '2026-06-23', '1010', 'Cash - Operating', 'CHECK #10482 - MERIDIAN STAFFING', 'CHK10482', NULL, 38200.00, 'Week 24 contract labor'),
  ('JE-2623', '2026-06-24', '1010', 'Cash - Operating', 'CHECK #10483 - SUMMIT OFFICE SUPPLY', 'CHK10483', NULL, 2140.00, 'PO-8867'),
  ('JE-2624', '2026-06-24', '1010', 'Cash - Operating', 'CHECK #10484 - CASCADE LOGISTICS', 'CHK10484', NULL, 21600.00, 'Freight - Jun'),
  ('JE-2625', '2026-06-25', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - BRIGHTWATER INDUSTRIES', 'INV-4495', 33200.00, NULL, NULL),
  ('JE-2626', '2026-06-26', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - DUNMORE WHOLESALE', 'INV-4497', 19800.00, NULL, NULL),
  ('JE-2627', '2026-06-27', '1010', 'Cash - Operating', 'CHECK #10485 - KESTREL LEGAL LLP', 'CHK10485', NULL, 4750.00, 'Matter FY26-114'),
  ('JE-2628', '2026-06-29', '1010', 'Cash - Operating', 'CHECK #10486 - DELTA FREIGHT SERVICES', 'CHK10486', NULL, 1890.00, 'Freight - Jun wk3-4'),
  ('JE-2629', '2026-06-30', '1010', 'Cash - Operating', 'PAYROLL ACH - PERIOD ENDING 06/27', 'ACH', NULL, 131200.00, NULL),
  ('JE-2630', '2026-06-30', '1010', 'Cash - Operating', 'CUSTOMER DEPOSIT - FAIRLIGHT MERCANTILE', 'INV-4502', 12400.00, NULL, NULL);

-- ---------------------------------------------------------------
-- Empty on purpose. Lab 2 imports budget-vs-actual-q2-fy26.csv into
-- this table; Lab 5 splits it into proper tables.
-- ---------------------------------------------------------------
CREATE TABLE budget_actual_raw (
  month      VARCHAR(7)    NOT NULL,
  department VARCHAR(40)   NOT NULL,
  account    VARCHAR(60)   NOT NULL,
  budget     DECIMAL(12,2) NOT NULL,
  actual     DECIMAL(12,2) NOT NULL
) ENGINE=InnoDB;

SELECT 'northwind is ready' AS status,
       (SELECT COUNT(*) FROM customers)  AS customers,
       (SELECT COUNT(*) FROM invoices)   AS invoices,
       (SELECT COUNT(*) FROM gl_entries) AS gl_entries;
